### ISSUE TITLE
PPA error

### ISSUE THREAD

**Issue by LinuxLiveMan** [linuxmint/mintupdate#188]
When I tring to add a ppa I get the following error message Linux mint 18.1:

sudo add-apt-repository ppa:nilarimogard/webupd8
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1547, in <module>
    codename = config_parser.get("general", "base_codename")
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'

**Comment by clefebvre** [comment]
Fixed.
