### ISSUE TITLE
Mintupdate's Kernel Module Can't Open With Liquorix Kernel

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#558]
Hi,

Mintupdate's kernel module can't open, if Liqourix kernel is active. Could You add Liquorix kernel support

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 33, in run
    self.application.build_kernels_list(kernels)
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 535, in build_kernels_list
    newest_supported_in_series))
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 153, in __init__
    Gtk.ToggleButton.set_active(button, not version_id or (not supported and ACTIVE_KERNEL_VERSION > version_id))
NameError: name 'ACTIVE_KERNEL_VERSION' is not defined
```

**Comment by kelebek333** [comment]
Issue solved by Mintupdate/5.5.3
