### ISSUE TITLE
Linux Mint 21 - mintupdate stuck "Processing updates"

### ISSUE THREAD

**Issue by kec19** [linuxmint/mintupdate#761]
**Describe the bug**
Update manager tray forever says "Checking for updates". The GUI lower left corner forever says "Processing updates".

**Screenshots**
No screenshot required.

**To Reproduce**
I log in. The tray icon appears without any action on my part. After noticing it always says "Checking for updates". I tried running mintupdate from a shell to see if any error message appear. I provide the output below. The GUI says "Processing updates" and after awhile, I get a "Update manager is not responding." dialog asking "Force quit" or "Wait".

/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1245: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1393: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  menuItem3.set_image(image)
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:731: DeprecationWarning: Gdk.threads_enter is deprecated
  Gdk.threads_enter()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:738: DeprecationWarning: Gdk.threads_leave is deprecated
  Gdk.threads_leave()
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/checkAPT.py", line 356, in <module>
    check.find_changes()
  File "/usr/lib/linuxmint/mintUpdate/checkAPT.py", line 43, in find_changes
    self.cache.upgrade(True) # dist-upgrade
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 372, in upgrade
    self._depcache.upgrade(dist_upgrade)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
-- Exception occurred in the refresh thread:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 838, in run
    self.application.builder.get_object("label_error_details").set_text(error_msg)
TypeError: Argument 1 does not allow None as a value

**Expected behavior**
I expect mintupdate to process updates in a reasonable amount of time and identify the suggested/required updates.

**Distribution:**
- [X ] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)
- [ x] 

**Software version:**
mintupdate version: 5.8.8

**Logs:**
Update manager (mintupdate) is locked up so I can't get the log via the suggested GUI actions.

**Crash report:**
Update manager (mintupdate) is locked up so I can't perform the suggested GUI actions.

**Additional context**
No additional context.

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by kec19** [comment]
In case it matters; cinnamon

**Comment by kec19** [comment]
After "sudo apt update" and "sudo apt upgrade", mintupdate is not locking up. The mintupdate console output differs from the output shown in the bug report. The new output is shown below.

/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1245: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1393: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  menuItem3.set_image(image)
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:731: DeprecationWarning: Gdk.threads_enter is deprecated
  Gdk.threads_enter()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:738: DeprecationWarning: Gdk.threads_leave is deprecated
  Gdk.threads_leave()

mintupdate -v
5.8.8
