### ISSUE TITLE
mintupdate: Unable to refresh list of updates on 5.9.5

### ISSUE THREAD

**Issue by mikeNG** [linuxmint/mintupdate#781]
**Describe the bug**
"Could not refresh the list of updates."

**To Reproduce**
1. Open update manager
2. Click on 'Refresh'
3. Wait
4. See error at the bottom

**Expected behavior**
Updater is able to refresh without issues.

**Distribution:**
- [x] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
5.9.5

**Logs:**
```
12.20@16:07 ++ Launching Update Manager
12.20@16:07 ++ Changes to the package cache detected, triggering refresh
12.20@16:07 ++ Starting refresh (local only)
12.20@16:07 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
12.20@16:07 -- Exception occurred in the refresh thread: <class 'OverflowError'>
```

**Crash report:**
```
Flatpak: done generating updates
-- Exception occurred in the refresh thread:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 1048, in run
    model.set_value(iter, UPDATE_SIZE, update.size)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1316, in set_value
    value = self._convert_value(column, value)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 921, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 208, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 257, in set_value
    _gi._gvalue_set(self, py_value)
OverflowError: 2893160559 not in range -2147483648 to 2147483647
```

**Additional context**
This started happening after upgrading to Mint 21.1

**Comment by clefebvre** [comment]
Fixed in 5.9.6
